### ISSUE TITLE
pico-dom vs picodom vs attodom?

### ISSUE THREAD

**Issue by brody2consult** [hville/pico-dom#1]
From <https://github.com/krausest/js-framework-benchmark/pull/352> I gather that pico-dom is now superseded by attodom. Please correct me if I am mistaken.

It also looks like this pico-dom project is different from <https://github.com/picodom/picodom>, getting really confusing now.

Assuming I am right: it would have been better if you would have simply renamed this project to attodom.

Suggested solution is to rename this project to something like pico-dom-1.x, rename attodom to pico-dom and then back to attodom (or put into its own organization).

**Comment by hville** [comment]
`Pico-dom` was an experiment at an alternative template-based scripts. It works but it quickly gets confusing as to what is a template and what is a component. Interesting but Abandoned.

`Picodom` came later and is completely independent with different objectives.

`attodom` is another experiment that is different from the other two. This is the active project with no name confusion.

Hope this clarifies.
